#!/usr/bin/env python3
"""Walk ~/backend-dev/ and rebuild viewer/manifest.json.

Run from inside ~/backend-dev/:

    python3 viewer/regenerate-manifest.py

Or from anywhere:

    python3 ~/backend-dev/viewer/regenerate-manifest.py

The script finds every *.md under known category dirs, derives a title from
the first `# heading` (or the filename), and writes the manifest the viewer
reads. Uses only the standard library — no pip install required.
"""
from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

CATEGORIES = ["notes", "cheatsheets", "flashcards", "sessions", "reviews", "meta"]
SKIP_NAMES = {"README.md", "COMMANDS.md", "session-state.md"}


def find_workspace_root(script_path: Path) -> Path:
    # Script lives at <workspace>/viewer/regenerate-manifest.py
    return script_path.resolve().parent.parent


def title_from_file(path: Path) -> str:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for raw in f:
                line = raw.strip()
                if line.startswith("# "):
                    return line[2:].strip()
                if line and not line.startswith("---"):
                    break
    except OSError:
        pass
    return path.stem.replace("-", " ").replace("_", " ").title()


def iso_mtime(path: Path) -> str:
    ts = path.stat().st_mtime
    return _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def collect(root: Path) -> list[dict]:
    entries: list[dict] = []
    for category in CATEGORIES:
        cat_dir = root / category
        if not cat_dir.is_dir():
            continue
        for md in sorted(cat_dir.rglob("*.md")):
            if md.name in SKIP_NAMES:
                continue
            rel = md.relative_to(root).as_posix()
            entries.append({
                "title": title_from_file(md),
                "path": rel,
                "category": category,
                "updated": iso_mtime(md),
            })
    return entries


def main(argv: list[str]) -> int:
    script_path = Path(__file__)
    root = find_workspace_root(script_path)
    if not root.exists():
        print(f"workspace not found: {root}", file=sys.stderr)
        return 1

    entries = collect(root)
    manifest = {
        "_notes": "Generated by regenerate-manifest.py. Don't hand-edit — re-run the script when files change.",
        "generated_at": _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "entries": entries,
    }

    out = script_path.parent / "manifest.json"
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
